version: "3"
services:
  web:
    build: .
    container_name: nszl/web
    depends_on:
          - sql
    ports :
      - 3000:3000
    volumes: 
          - .:/docker_node #maps current host dir to docker working dir
          - /docker_node/node_modules


  sql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: sql
    restart: always
    volumes:
      - data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_HOST: '%' #dangerous, allows every ip to connect. remove on prod
    ports:
      - 3306:3306


  phpmyadmin:
    depends_on:
      - sql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: sql
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
volumes:
  data :
